### ISSUE TITLE
(mobile Devices) btn.addEventListener("click") causes problems with other interactive elements

### ISSUE THREAD

**Issue by DasAuryn** [jdsantos/maplibre-gl-measures#1]
MeasuresControl causes Problems, if you have other clickable elements, like markers on map.

This behaviour is only on mobile Browsers:

Console:

Unable to preventDefault inside passive event listener invocation.

**Comment by jdsantos** [comment]
Hi there @DasAuryn,

First of all, thank you very much for your contribution. I believe it is an existing bug within the mapbox-draw plugin. You can check that the same bug occurs when only using mapbox-draw:

https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/

However, I'm going to try to find a solution for this.

Cheers,

Jorge

**Comment by jdsantos** [comment]
@DasAuryn also pointed out this PR that might solve this problem:

https://github.com/mapbox/mapbox-gl-draw/pull/869

**Comment by PedroVenancio** [comment]
Hi @jdsantos 

Since the PR has almost 4 years without being merged, and it seems to fix the issue, maybe you could apply the changes in a personal fork? I don't know, but this is an important issue.

Thanks for your work @jdsantos !

**Comment by DasAuryn** [comment]
> Hi @jdsantos
> 
> Apparently this issue was fixed in Mapbox Draw: [mapbox/mapbox-gl-draw@v1.3.0...v1.4.0](https://github.com/mapbox/mapbox-gl-draw/compare/v1.3.0...v1.4.0)

I can confirm, it works now.
