### ISSUE TITLE
draw.getMode is not a function

### ISSUE THREAD

**Issue by 2803media** [jdsantos/maplibre-gl-measures#13]
Hi I just found a bug, this code fired an error:

```
var draw = new maplibreGLMeasures.default(options);
        map.addControl(draw, 'top-right');
        //disable click on map when drawing

        map.on('draw.modechange', function(e) {
            showHideDrawingIndicator();
        });

        function showHideDrawingIndicator() {
            if (draw.getMode() === 'draw_line_string' || draw.getMode() === 'draw_polygon') {
                map.addControl(drawingActive, 'top-left');
            } else if (draw.getMode() === 'simple_select') {
                map.removeControl(drawingActive);
            }
        }


        class DrawingActiveControl {
            onAdd(map) {
                var indicator = document.getElementsByClassName('drawing-active-control')
                if (indicator.length === 0) {
                    this.map = map;
                    this.container = document.createElement('div');
                    this.container.className = 'drawing-active-control';
                    this.container.innerHTML = '<strong>Drawing Tool Active</strong><br/>' +
                        '<small>(Hit Enter or double-click to finish)</small>';
                    return this.container;
                }
            }

            onRemove() {
                try {
                    this.container.parentNode.removeChild(this.container);
                    this.map = undefined;
                } catch (e) {}
            }
        }

        var drawingActive = new DrawingActiveControl();
        
```

```
Uncaught TypeError: draw.getMode is not a function
    at showHideDrawingIndicator (xxx-maplibre.php:532:22)
    at Map.<anonymous> (xxx-maplibre.php:528:13)
    at Map.fire (maplibre-gl.js:31:8902)
    at o.fire (maplibre-gl-measures.js:2:20250)
    at Object.l [as changeMode] (maplibre-gl-measures.js:2:22418)
    at K.changeMode (maplibre-gl-measures.js:2:12151)
    at K.clickOnVertex (maplibre-gl-measures.js:2:56510)
    at jt.onTap.jt.onClick (maplibre-gl-measures.js:2:56761)
    at Object.<anonymous> (maplibre-gl-measures.js:2:20676)
    at i (maplibre-gl-measures.js:2:492)
```

**Comment by CristianAmici** [comment]
> Hi I just found a bug, this code fired an error:
> 
> ```
> var draw = new maplibreGLMeasures.default(options);
>         map.addControl(draw, 'top-right');
>         //disable click on map when drawing
> 
>         map.on('draw.modechange', function(e) {
>             showHideDrawingIndicator();
>         });
> 
>         function showHideDrawingIndicator() {
>             if (draw.getMode() === 'draw_line_string' || draw.getMode() === 'draw_polygon') {
>                 map.addControl(drawingActive, 'top-left');
>             } else if (draw.getMode() === 'simple_select') {
>                 map.removeControl(drawingActive);
>             }
>         }
> 
> 
>         class DrawingActiveControl {
>             onAdd(map) {
>                 var indicator = document.getElementsByClassName('drawing-active-control')
>                 if (indicator.length === 0) {
>                     this.map = map;
>                     this.container = document.createElement('div');
>                     this.container.className = 'drawing-active-control';
>                     this.container.innerHTML = '<strong>Drawing Tool Active</strong><br/>' +
>                         '<small>(Hit Enter or double-click to finish)</small>';
>                     return this.container;
>                 }
>             }
> 
>             onRemove() {
>                 try {
>                     this.container.parentNode.removeChild(this.container);
>                     this.map = undefined;
>                 } catch (e) {}
>             }
>         }
> 
>         var drawingActive = new DrawingActiveControl();
>         
> ```
> 
> ```
> Uncaught TypeError: draw.getMode is not a function
>     at showHideDrawingIndicator (xxx-maplibre.php:532:22)
>     at Map.<anonymous> (xxx-maplibre.php:528:13)
>     at Map.fire (maplibre-gl.js:31:8902)
>     at o.fire (maplibre-gl-measures.js:2:20250)
>     at Object.l [as changeMode] (maplibre-gl-measures.js:2:22418)
>     at K.changeMode (maplibre-gl-measures.js:2:12151)
>     at K.clickOnVertex (maplibre-gl-measures.js:2:56510)
>     at jt.onTap.jt.onClick (maplibre-gl-measures.js:2:56761)
>     at Object.<anonymous> (maplibre-gl-measures.js:2:20676)
>     at i (maplibre-gl-measures.js:2:492)
> ```

Hi, this is because maplibreGLMeasures use MapboxDraw and is a property of maplibreGLMeasures , Therefore, in the code you can´t call draw.getMode() in the firs step, but you can use in your case **draw._drawCtrl.getMode()**
