### ISSUE TITLE
Measures numbers are not visible

### ISSUE THREAD

**Issue by VardgesHA777** [jdsantos/maplibre-gl-measures#14]
I installed maplibre-gl-measures in my project, and gave this configs to it 

  const options = {
      showDistance: true,
      lang: {
        areaMeasurementButtonTitle: 'Measure area',
        lengthMeasurementButtonTitle: 'Measure length',
        clearMeasurementsButtonTitle: 'Clear measurements',
      },
      units: 'imperial', // Or metric, the default
    };
    map.current.addControl(new MeasuresControl(options), 'top-left');
    
    I can use measure  but it doesn't write distance numbers on it, seems everthing working except distance numbers, also having this kind of error in console, 
    
    layers.layer-draw-labels.layout.text-field: use of "text-field" requires a style "glyphs" property
    at Object.An [as emitValidationErrors]

**Comment by bino-xentity** [comment]
set min zoom : 15

**Comment by jdsantos** [comment]
Hi @VardgesHA777!

Did you get it to work? Did @bino-xentity solution worked for you?
That error appears to be related to a missing glyphs property on the map:
```

new maplibregl.Map({
            ...
            glyphs: "https://fonts.openmaptiles.org/{fontstack}/{range}.pbf",
            ...
          });
```

If you run into any more trouble check out the full working example here [docs/index.html](https://github.com/jdsantos/maplibre-gl-measures/blob/main/docs/index.html)
