### ISSUE TITLE
Measurement result not display

### ISSUE THREAD

**Issue by gisfinder** [jdsantos/maplibre-gl-measures#15]
Maplibre version: 2.4.0
Error message :
maplibre-gl.js:31 Error {message: 'Unimplemented type: 3'}message: "Unimplemented type: 3"[[Prototype]]: Objectconstructor: ƒ Error()message: ""name: "Error"toString: ƒ toString()length: 0name: "toString"arguments: （…）caller: （…）[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0][[Prototype]]: Object
fire @ maplibre-gl.js:31
fire @ maplibre-gl.js:31
fire @ maplibre-gl.js:31
_tileLoaded @ maplibre-gl.js:35
（匿名） @ maplibre-gl.js:35
processTask @ maplibre-gl.js:31
receive @ maplibre-gl.js:31

the code pen is as   https://codepen.io/gisfinder/pen/gOQNQwV?editors=1000

**Comment by bino-xentity** [comment]
set min zoom : 15
