### ISSUE TITLE
Can I use this with Typescript?

### ISSUE THREAD

**Issue by eusolomax** [jdsantos/maplibre-gl-measures#21]
I tried to import the **MeasuresControl** module, but I'm receiving this error:

> Could not find a declaration file for module 'maplibre-gl-measures'. '/home/.../node_modules/maplibre-gl-measures/src/maplibre-gl-measures.js' implicitly has an 'any' type.
> 
>   Try `npm i --save-dev @types/maplibre-gl-measures` if it exists or add a new declaration (.d.ts) file containing `declare module 'maplibre-gl-measures';

As this package doesn't seems to have a _@types/maplibre-gl-measures_ [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

I have tried to add into my node_modules (inside @types folder)
a folder called _maplibre-gl-measures_ > _index.d.ts_

That has:
`declare module 'maplibre-gl-measures';`

as a workaround to make it work... 

but now, I receive just a blank screen and a console.log error about 

![image](https://github.com/user-attachments/assets/a6280363-bb64-4b08-b88c-dc1b6f9d8433)

**Comment by jdsantos** [comment]
Hi there @eusolomax!

I tried to use this in a vue + vite + ts project and it throws the exact error you described. I managed to make it work by changing some settings in my vite/ts environment:

In the 'tsconfig.app.json' and 'tsconfig.json', I included this option: 

```
  "compilerOptions": {
    "esModuleInterop": true
  },
```

and in my vite.config.ts I included the 'define' section with the definition of global:

```
define: {
    // "process.env": process.env,
    // // By default, Vite doesn't include shims for NodeJS/
    // // necessary for segment analytics lib to work
    global: 'globalThis',
  },
```

Seems to be working fine after these changes:
![image](https://github.com/user-attachments/assets/55a66aab-29e0-4473-afb3-c1df0eaf5e38)

Here is the project that I created as demo:

[hello-world.zip](https://github.com/user-attachments/files/16457993/hello-world.zip)

Hope this helps!

Cheers, 

Jorge

**Comment by DasAuryn** [comment]
I use it in typescript:
add
//@ts-ignore before import.

**Comment by jdsantos** [comment]
Thanks for your feedback @DasAuryn 🙌

Cheers,

Jorge

**Comment by eusolomax** [comment]
I've made it work using both solutions, I'm not a big of **@ts-ignore**, but it does the job.
Thanks, guys!
