### ISSUE TITLE
Wrong area measurement with version 0.0.6

### ISSUE THREAD

**Issue by PedroVenancio** [jdsantos/maplibre-gl-measures#8]
Hi @jdsantos 

It seems that in version 0.0.6 it was introduced an error in area measurement.

Here is the sample demo: https://codepen.io/PedroNGV/pen/GRBvpKX

- With version 0.0.5
![imagem](https://user-images.githubusercontent.com/1331581/212503158-a74b93b3-8de5-4ccf-9b8e-a4d5f79a400d.png)

- With version 0.0.6
![imagem](https://user-images.githubusercontent.com/1331581/212503189-791666ec-71b2-4077-927e-b189f1239243.png)

Apparently, the conversion from m2 to km2 is being done dividing by 1.000 instead of dividing by 1.000.000.

**Comment by jdsantos** [comment]
Hi there @PedroVenancio!

First of all, thanks for noticing that! I'm using this plugin to convert units: https://github.com/convert-units/convert-units and I trusted it could handle m2 and mi2 without a fuss.
I'll work on a fix right away.

Cheers,

Jorge

**Comment by PedroVenancio** [comment]
Thank you very much @jdsantos !

That's perfect now!
