### ISSUE TITLE
Draw layer on top of all layers

### ISSUE THREAD

**Issue by PedroVenancio** [jdsantos/maplibre-gl-measures#9]
Hi @jdsantos 

Is there any possibility to force the draw layers to be at the top of all layers on map?

![imagem](https://user-images.githubusercontent.com/1331581/212573832-d5fc4c2a-62e4-43e5-b693-fdb49025264e.png)

Sample code: https://codepen.io/PedroNGV/pen/qByXVxo

I've found several threads about this, but how can be applied to the plugin?
https://github.com/mapbox/mapbox-gl-draw/issues/600
https://github.com/mapbox/mapbox-gl-draw/issues/992

It seems to me that the measurement layers on top should be the default behaviour.

Thanks!

**Comment by jdsantos** [comment]
Hi @PedroVenancio,

Great idea! ;) We would need probably something like [map.moveLayer](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#movelayer) to reorder layers, right?

Cheers,

Jorge

**Comment by PedroVenancio** [comment]
Hi @jdsantos 

> We would need probably something like [map.moveLayer](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#movelayer) to reorder layers, right?

Yes, I think so. Do you think it is possible directly from de plugin?

Thanks!

**Comment by jdsantos** [comment]
Hi there @PedroVenancio

It took some time (LOL) but I finally found time to fix this. It should be working in version 0.0.9. 

Many thanks for your feedback!

**Comment by PedroVenancio** [comment]
Hi @jdsantos 

Thank you very much, it works great now!

![imagem](https://github.com/jdsantos/maplibre-gl-measures/assets/1331581/39a8f932-954b-4dcd-86b6-bb5a26fa1d10)
